import '@/style/globals.css'
import { ReactNode } from 'react'
import { MainLayout } from '@/components/MainLayout'
import { Providers } from '@/components/Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <div>
      <Providers>
        {/* / @ts-expect-error -> Async Server Component */}
        <MainLayout>{children}</MainLayout>
      </Providers>
    </div>
  )
}
