import { Providers } from '@/components/Providers'
import '@/style/globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="w-screen h-screen bg-white">{children}</body>
      </Providers>
    </html>
  )
}
