import { Providers } from '@/components/Providers'
import '@/style/globals.css'
import { ReactNode } from 'react'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  leftcontentsidebar: ReactNode
  children: ReactNode
  rightcontentsidebar: ReactNode
}

export default async function Layout({
  children,
  leftcontentsidebar,
  rightcontentsidebar,
}: Props) {
  return (
    <div className="flex flex-row w-full h-full ">
      {leftcontentsidebar}
      {/* <div className=" w-full bg-green-500 h-full px-8 py-4 p-3">{children}</div> */}
      <div className="flex flex-row w-full h-full px-3 pt-3 pb-2">
        {children}
      </div>
      {rightcontentsidebar}
    </div>
  )
}
