import { Providers } from '@/components/Providers'
import '@/style/globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Hope Aba',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Providers>
        <body className="w-screen h-screen">{children}</body>
      </Providers>
    </html>
  )
}
