'use client'
import { Providers } from '@/components/Providers'
import { useAuth } from '@/hooks/useAuth'
import { useServerAuth } from '@/hooks/useServerAuth'
import '@/style/globals.css'
import { redirect, usePathname } from 'next/navigation'
import { ReactNode } from 'react'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

interface RootLayoutProps {
  layoutleftsidebar: ReactNode
  layoutheader: ReactNode
  children: ReactNode
}

export default function RootLayout({
  children,
  layoutleftsidebar,
  layoutheader,
}: RootLayoutProps) {
  const { authenticatedUser } = useAuth()

  const pathName = usePathname()
  console.log('pathName', pathName)

  if (!authenticatedUser && pathName !== '/login') {
    redirect('/login')
  }

  return (
    <html lang="en">
      <Providers>
        <body className="w-screen h-screen bg-white flex flex-row">
          <div className="z-50 w-fit h-fit">{layoutleftsidebar}</div>

          <div className="flex flex-col w-full h-full">
            <header>{layoutheader}</header>

            <main id="main" className="h-full w-full bg-white flex flex-row ">
              {children}
            </main>
          </div>
        </body>
      </Providers>
    </html>
  )
}
