import { ReactNode } from 'react'

export const metadata = {
  title: 'Hope Aba',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  layoutleftsidebar: ReactNode
  layoutheader: ReactNode
  children: ReactNode
}

export default async function RootLayout({
  children,
  layoutleftsidebar,
  layoutheader,
}: RootLayoutProps) {
  return (
    <div className="w-full h-full bg-white flex flex-row">
      <div className="z-50 w-fit h-fit">{layoutleftsidebar}</div>

      <div className="flex flex-col w-full h-full">
        <header>{layoutheader}</header>

        <main id="main" className="h-full w-full bg-white flex flex-row ">
          {children}
        </main>
      </div>
    </div>
  )
}
